version: "3.8"

networks:
  vpnnet:

services:
  nordvpn:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    environment:
      - USER=${NORDVPN_USER}
      - PASS=${NORDVPN_PASS}
      - CONNECT=Turkey
      - TECHNOLOGY=OpenVPN
    restart: unless-stopped
    networks:
      - vpnnet

  resolver:
    build: .
    depends_on:
      - nordvpn
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    ports:
      - "6288:6288"
    restart: unless-stopped
    networks:
      - vpnnet
