version: "3.8"

networks:
  vpnnet:

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASS}
      - SERVER_COUNTRIES=Turkey
    restart: unless-stopped
    networks:
      - vpnnet

  resolver:
    build: .
    depends_on:
      - gluetun
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    ports:
      - "6288:6288"
    restart: unless-stopped
    networks:
      - vpnnet
